import {
  pgTable,
  text,
  integer,
  boolean,
  timestamp,
  date,
  primaryKey,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ============================================================
// Better Auth tables — generated by `npx @better-auth/cli generate`
// against src/lib/auth.ts. Do not hand-edit column names/types;
// re-run the generator if you change the Better Auth config.
// ============================================================

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)]
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    issuer: text("issuer").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)]
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)]
);

export const userRelations = relations(user, ({ many, one }) => ({
  sessions: many(session),
  accounts: many(account),
  habits: many(habits),
  gardenState: one(gardenState, {
    fields: [user.id],
    references: [gardenState.userId],
  }),
  unlockedPlants: many(unlockedPlants),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

// ============================================================
// App tables
// ============================================================

// ---------- habits ----------
export const habits = pgTable("habits", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  targetPerWeek: integer("target_per_week").notNull().default(7),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  archived: boolean("archived").notNull().default(false),
});
export type Habit = typeof habits.$inferSelect;

// ---------- completions ----------
// One row per habit per day it was completed. `completedOn` + `habitId`
// unique together so a habit can't be double-counted on the same day.
export const completions = pgTable(
  "completions",
  {
    id: text("id").primaryKey(),
    habitId: text("habit_id")
      .notNull()
      .references(() => habits.id, { onDelete: "cascade" }),
    completedOn: date("completed_on").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("completions_habit_day_unique").on(
      table.habitId,
      table.completedOn
    ),
  ]
);

// ---------- garden state ----------
// One row per user tracking their running growth score.
export const gardenState = pgTable("garden_state", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  growthPoints: integer("growth_points").notNull().default(0),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// ---------- plants ----------
// Static catalog of unlockable plants, seeded once.
export const plants = pgTable("plants", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  unlockThreshold: integer("unlock_threshold").notNull(),
  emoji: text("emoji").notNull(),
});

// ---------- unlocked plants ----------
export const unlockedPlants = pgTable(
  "unlocked_plants",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    plantId: text("plant_id")
      .notNull()
      .references(() => plants.id, { onDelete: "cascade" }),
    unlockedAt: timestamp("unlocked_at").defaultNow().notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.plantId] })]
);

export const habitsRelations = relations(habits, ({ one, many }) => ({
  user: one(user, { fields: [habits.userId], references: [user.id] }),
  completions: many(completions),
}));

export const completionsRelations = relations(completions, ({ one }) => ({
  habit: one(habits, {
    fields: [completions.habitId],
    references: [habits.id],
  }),
}));

export const gardenStateRelations = relations(gardenState, ({ one }) => ({
  user: one(user, { fields: [gardenState.userId], references: [user.id] }),
}));

export const plantsRelations = relations(plants, ({ many }) => ({
  unlockedBy: many(unlockedPlants),
}));

export const unlockedPlantsRelations = relations(
  unlockedPlants,
  ({ one }) => ({
    user: one(user, {
      fields: [unlockedPlants.userId],
      references: [user.id],
    }),
    plant: one(plants, {
      fields: [unlockedPlants.plantId],
      references: [plants.id],
    }),
  })
);
